let arguments = [
  "-c",
  "/Users/nate/Projects/swift-argument-parser/Sources/ArgumentParser/Completions/BashCompletionsGenerator.swift",
  "/Users/nate/Projects/swift-argument-parser/Sources/ArgumentParser/Completions/CompletionsGenerator.swift",
  "/Users/nate/Projects/swift-argument-parser/Sources/ArgumentParser/Completions/FishCompletionsGenerator.swift",
  "/Users/nate/Projects/swift-argument-parser/Sources/ArgumentParser/Completions/ZshCompletionsGenerator.swift",
  "/Users/nate/Projects/swift-argument-parser/Sources/ArgumentParser/Parsable Properties/Argument.swift",
  "/Users/nate/Projects/swift-argument-parser/Sources/ArgumentParser/Parsable Properties/ArgumentHelp.swift",
  "/Users/nate/Projects/swift-argument-parser/Sources/ArgumentParser/Parsable Properties/CompletionKind.swift",
  "/Users/nate/Projects/swift-argument-parser/Sources/ArgumentParser/Parsable Properties/Errors.swift",
  "/Users/nate/Projects/swift-argument-parser/Sources/ArgumentParser/Parsable Properties/Flag.swift",
  "/Users/nate/Projects/swift-argument-parser/Sources/ArgumentParser/Parsable Properties/NameSpecification.swift",
  "/Users/nate/Projects/swift-argument-parser/Sources/ArgumentParser/Parsable Properties/Option.swift",
  "/Users/nate/Projects/swift-argument-parser/Sources/ArgumentParser/Parsable Types/CommandConfiguration.swift",
  "/Users/nate/Projects/swift-argument-parser/Sources/ArgumentParser/Parsable Types/EnumerableFlag.swift",
  "/Users/nate/Projects/swift-argument-parser/Sources/ArgumentParser/Parsable Types/ExpressibleByArgument.swift",
  "/Users/nate/Projects/swift-argument-parser/Sources/ArgumentParser/Parsable Types/ParsableArguments.swift",
  "/Users/nate/Projects/swift-argument-parser/Sources/ArgumentParser/Parsable Types/ParsableArgumentsValidation.swift",
  "/Users/nate/Projects/swift-argument-parser/Sources/ArgumentParser/Parsable Types/ParsableCommand.swift",
  "/Users/nate/Projects/swift-argument-parser/Sources/ArgumentParser/Parsing/ArgumentDecoder.swift",
  "/Users/nate/Projects/swift-argument-parser/Sources/ArgumentParser/Parsing/ArgumentDefinition.swift",
  "/Users/nate/Projects/swift-argument-parser/Sources/ArgumentParser/Parsing/ArgumentSet.swift",
  "/Users/nate/Projects/swift-argument-parser/Sources/ArgumentParser/Parsing/CommandParser.swift",
  "/Users/nate/Projects/swift-argument-parser/Sources/ArgumentParser/Parsing/InputOrigin.swift",
  "/Users/nate/Projects/swift-argument-parser/Sources/ArgumentParser/Parsing/Name.swift",
  "/Users/nate/Projects/swift-argument-parser/Sources/ArgumentParser/Parsing/Parsed.swift",
  "/Users/nate/Projects/swift-argument-parser/Sources/ArgumentParser/Parsing/ParsedValues.swift",
  "/Users/nate/Projects/swift-argument-parser/Sources/ArgumentParser/Parsing/ParserError.swift",
  "/Users/nate/Projects/swift-argument-parser/Sources/ArgumentParser/Parsing/SplitArguments.swift",
  "/Users/nate/Projects/swift-argument-parser/Sources/ArgumentParser/Usage/HelpCommand.swift",
  "/Users/nate/Projects/swift-argument-parser/Sources/ArgumentParser/Usage/HelpGenerator.swift",
  "/Users/nate/Projects/swift-argument-parser/Sources/ArgumentParser/Usage/MessageInfo.swift",
  "/Users/nate/Projects/swift-argument-parser/Sources/ArgumentParser/Usage/UsageGenerator.swift",
  "/Users/nate/Projects/swift-argument-parser/Sources/ArgumentParser/Utilities/SequenceExtensions.swift",
  "/Users/nate/Projects/swift-argument-parser/Sources/ArgumentParser/Utilities/StringExtensions.swift",
  "/Users/nate/Projects/swift-argument-parser/Sources/ArgumentParser/Utilities/Tree.swift",
  "-emit-module-path",
  "/Users/nate/Projects/swift-argument-parser/.build/x86_64-apple-macosx/debug/ArgumentParser.build/Parsable Properties/OptionGroup~partial.swiftmodule",
   "-emit-module-source-info-path",
  "/Users/nate/Projects/swift-argument-parser/.build/x86_64-apple-macosx/debug/ArgumentParser.build/Parsable Properties/OptionGroup~partial.swiftsourceinfo",
   "-target",
  "x86_64-apple-macosx10.10",
  "-sdk",
  "/Applications/Xcode.app/Contents/Developer/Platforms/MacOSX.platform/Developer/SDKs/MacOSX11.1.sdk",
  "-I",
  "/Users/nate/Projects/swift-argument-parser/.build/x86_64-apple-macosx/debug",
  "-I",
  "/Applications/Xcode.app/Contents/Developer/Platforms/MacOSX.platform/Developer/usr/lib",
  "-F",
  "/Applications/Xcode.app/Contents/Developer/Platforms/MacOSX.platform/Developer/Library/Frameworks",
  "-color-diagnostics",
  "-enable-testing",
  "-g",
  "-module-cache-path",
  "/Users/nate/Projects/swift-argument-parser/.build/x86_64-apple-macosx/debug/ModuleCache",
  "-swift-version",
  "5",
  "-Onone",
  "-D",
  "SWIFT_PACKAGE",
  "-D",
  "DEBUG",
  "-parse-as-library",
  "-module-name",
  "ArgumentParser",
  "-o",
  "/Users/nate/Projects/swift-argument-parser/.build/x86_64-apple-macosx/debug/ArgumentParser.build/Parsable Properties/OptionGroup.swift.o",
  "-index-store-path",
  "/Users/nate/Projects/swift-argument-parser/.build/x86_64-apple-macosx/debug/index/store",
]
