#if !canImport(ObjectiveC)
import XCTest

extension PrefixTrieTests {
    // DO NOT MODIFY: This is autogenerated, use:
    //   `swift test --generate-linuxmain`
    // to regenerate.
    static let __allTests__PrefixTrieTests = [
        ("testManyMatchingPrefixes", testManyMatchingPrefixes),
        ("testSimpleTrie", testSimpleTrie),
        ("testUpdating", testUpdating),
    ]
}

extension SwiftDriverTests {
    // DO NOT MODIFY: This is autogenerated, use:
    //   `swift test --generate-linuxmain`
    // to regenerate.
    static let __allTests__SwiftDriverTests = [
        ("testParseErrors", testParseErrors),
        ("testParsing", testParsing),
    ]
}

public func __allTests() -> [XCTestCaseEntry] {
    return [
        testCase(PrefixTrieTests.__allTests__PrefixTrieTests),
        testCase(SwiftDriverTests.__allTests__SwiftDriverTests),
    ]
}
#endif
